image:
  file: .gitpod.Dockerfile
checkoutLocation: '.'
#tasks:
#  - name: Clean root and grab useful exercises.
#    before: |
#      rm -rfv ./{*,.*}
#      sudo mv /home/gitpod/dbt_audiance_measurment/* .