version: 2

sources:
    - name: training
      description: 'Timestamps and Schedule tables used as source for our project'
      database: "{{ target.database }}"
      schema: PUBLIC
      tables:
       - name: timestamps
         description: 'Raw event data coming from the measuring boxes'

       - name: schedule
         description: 'TV program'


models:
  - name: session
    description: Sessions descibe which channel has been watch from a start time to an end time for a given user. Typically, each user contains multiple sessions per day. Sessions are created from TIMESTAMPS data.
    columns:
      - name: users
        tests:
          - not_null

  - name: enriched_session
    description: Enriched sessions are sessions that have been joined with TV program data. Each program watched on a channel will generate a new enriched session. One session can result in multiple enriched sessions.
    columns:
      - name: users
        tests:
          - not_null
      - name: common_channel
        tests:
          - not_null

  - name: agg_per_user
    description: This aggregate calculates statistics of enriched sessions per user
    columns:
      - name: unique_id
        tests:
          - unique
          - not_null

  - name: agg_per_program
    description: This aggregate calculates statistics of enriched sessions per program
    columns:
      - name: unique_id
        tests:
          - unique
          - not_null
  
  - name: least_popular_program
    description: This model calculates the least popular TV show
    columns: 
    - name: program
      description: The name of the TV show
      tests:
      - unique
      - not_null
      - relationships:
          to: ref('agg_per_program')
          field: 'program'
    - name: total_time_minutes
      description: The total time that the TV show was watched




